### ISSUE TITLE
Flow Chart Diagrams in Coricamu

### ISSUE THREAD

**Issue by josphh** [danth/coricamu#4]
### Description

Browsing Reddit, I noticed GitHub now has a new feature to write in Flow Chart Diagrams (and more) using [Mermaid](https://github.com/mermaid-js/mermaid). Would this be possible with Coricamu?

### Advantages

- Allows easier representation of data
- Bypasses need for using an image created outside of markdown
- Looks cool

**Comment by danth** [comment]
I already thought about this while writing [a post about the Nixpkgs branching system](https://danth.pwak.org/posts/post/understanding_the_nixpkgs_branching_system.html), which includes a flowchart generated using a similar tool:

![Example of an auto-generated flowchart.](https://danth.pwak.org/images/nixpkgs_branching.svg)

## Implementation

I think it would be easiest and most beneficial to have diagrams defined separately from the main content, like this:

```nix
{
  diagrams.example = builtins.readFile ./example_diagram;
}
```

That way the conversion from text to SVG can happen at build-time, and we can serve the generated SVG file so that Mermaid's Javascript does not need to be embedded into the page. That way visitors can load diagrams without having Javascript enabled, and the page will still be fast to load, as no Javascript files need to be transferred to the browser.

Generated diagrams would be served at a known path so that they can be inserted like a normal image:

```md
![A diagram to show...](/diagrams/example.svg)
```

Which works in HTML too:

```html
<img alt="A diagram to show..." src="/diagrams/example.svg">
```

(`/diagrams/example.svg` corresponds to `diagrams.example` from the Nix code above.)

**Comment by danth** [comment]
Perhaps [transforming diagrams within Markdown](https://github.com/mermaid-js/mermaid-cli#transform-a-markdown-file-with-mermaid-diagrams) would be more user-friendly for writing. However it would require more changes to Coricamu, but those may be necessary for other advanced features in the future too.
